export const CANVAS_SIZE = {
	MIN_WIDTH: 300,
	MAX_WIDTH: 500,
	PADDING: 0.9
};

const SCALE_MULTIPLIER = 3;

export const BUILDING_SIZE = {
	WIDTH: 180 * SCALE_MULTIPLIER,
	HEIGHT: 600 * SCALE_MULTIPLIER,
	ASPECT_RATIO: 180 / 600
};

export const WORLD_SIZE = {
	REFERENCE_WIDTH: 600
};

export const COLLISION_SPACE = {
	DEFAULT_CELL_SIZE: 10 * SCALE_MULTIPLIER
};

export const PLAYER_SIZE = {
	WIDTH: 32 * 2,
	HEIGHT: 32 * 2
};
